error: Add error prefix API
Add an API to prefix an already set error with a caller-centric
message.

If multiple errors are set, all are prefixed individually.

Signed-off-by: Peter Crosthwaite <crosthwaite.peter@gmail.com>